<?php

namespace AC\ColumnFactory\User;

use AC\Column\ColumnFactory;
use AC\Setting\ComponentCollection;
use AC\Setting\Config;
use AC\Setting\Formatter;
use AC\Setting\FormatterCollection;

class VisualEditingFactory extends ColumnFactory
{

    protected function get_label(): string
    {
        return __('Visual Editor', 'codepress-admin-columns');
    }

    public function get_type(): string
    {
        return 'column-rich_editing';
    }

    protected function get_formatters(
        ComponentCollection $components,
        Config $config,
        FormatterCollection $formatters
    ): FormatterCollection {
        $formatters->add(new Formatter\User\HasRichEditing());
        $formatters->add(new Formatter\YesNoIcon());

        return parent::get_formatters($components, $config, $formatters); // TODO: Change the autogenerated stub
    }

}