#!/bin/bash

langs=( ar da de es en-nz fa fr he hu it ja nl pl pt-br ro ru sv-se zh-cn )
exts=( po mo )

mkdir -p "languages"

if [ -d languages ]
then
    cd languages

    for ext in "${exts[@]}"
    do :
        rm -rf "*.${ext}"
    done
fi

for lang in "${langs[@]}"
do :
    url="https://translate.wordpress.org/projects/wp--plugins/codepress-admin-columns/stable/${lang}/default/export-translations?format="
echo -e  url
    for ext in "${exts[@]}"
    do :
        IFS="-" langparts=($lang)

        if [ ${#langparts[1]} -eq 0 ]; then
            langparts[1]=${langparts[0]}
        fi

        ulang=$(echo "${langparts[1]}" | tr '[:lower:]' '[:upper:]')
        locale=${langparts[0]}_$ulang

        echo $url$ext
        #curl $url$ext --silent --output codepress-admin-columns-$locale.$ext &
    done
done

wait