#!/bin/bash

languages=(
    'ar::ar_AR'
    'bg::bg_BG'
    'da::da_DK'
    'de::de_DE'
    'es::es_ES'
    'en-nz::en_NZ'
    'fa::fa_IR'
    'fr::fr_FR'
    'he::he_IL'
    'hu::hu_HU'
    'it::it_IT'
    'ja::ja_JA'
    'nl::nl_NL'
    'nb::nb_NO'
    'pl::pl_PL'
    'pt-br::pt_BR'
    'pt::pt_PT'
    'ro::ro_RO'
    'ru::ru_RU'
    'sv::sv_SE'
    'tr::tr_TR'
    'zh-cn::zh_CN'

)
exts=( po mo )

mkdir -p "languages"

if [ -d languages ]
then
    cd languages

    for ext in "${exts[@]}"
    do :
        rm -rf "*.${ext}"
    done
fi

echo "Starting download of language files..."

for index in "${languages[@]}" ; do
    KEY="${index%%::*}"
    LOCALE="${index##*::}"

    #url="https://translate.wordpress.org/projects/wp-plugins/codepress-admin-columns/stable/${KEY}/default/export-translations/"
    url="https://translate.wordpress.org/projects/wp-plugins/codepress-admin-columns/stable/${KEY}/default/export-translations/?format="

    echo "Downloading language ${LOCALE}"

    for ext in "${exts[@]}"; do
        curl $url$ext --silent --output codepress-admin-columns-$LOCALE.$ext &
    done

    sleep 1

done

wait