<?php

namespace AC\ColumnFactory\Media;

use AC\Column\ColumnFactory;
use AC\Setting\ComponentCollection;
use AC\Setting\Config;
use AC\Setting\Formatter\Media\FileSize;
use AC\Setting\FormatterCollection;

class FileSizeFactory extends ColumnFactory
{

    public function get_type(): string
    {
        return 'column-file_size';
    }

    protected function get_label(): string
    {
        return __('File Size', 'codepress-admin-columns');
    }

    protected function get_formatters(
        ComponentCollection $components,
        Config $config,
        FormatterCollection $formatters
    ): FormatterCollection {
        $formatters->add(new FileSize());

        return parent::get_formatters($components, $config, $formatters); // TODO: Change the autogenerated stub
    }

}